const COLORS = {
  // BRAND COLORS
  BRAND_PRIMARY: "#618666",
  BG_BRAND: "#4B6A4F",

  // BACKGROUND COLORS
  BG_PRIMARY: "#FFF",
  BG_SECONDARY: "#F6F6F6",
  BG_TERTIARY: "#EEE",
  BG_TRUEGREY: "#E2E2E2",
  BG_GREEN: "#D2E0D4",
  BG_PURPLE: "#DCCFFC",
  BG_ORANGE: "#FAC2AF",
  BG_LIGHT_GREEN: "#E8F0E9",
  BG_LIGHT_PURPLE: "#EAE3FC",
  BG_LIGHT_ORANGE: "#FFE9E0",
  // CONTENT COLORS

  TEXT_PRIMARY: "#121212",
  TEXT_TERTIARY: "#757575",
  TEXT_DISABLED_PRIMARY: "#AFAFAF",
  TEXT_INVERSE_PRIMARY: "#F6F6F6",
  TEXT_SECONDARY: "#545454",
  TEXT_WHITE: "#FFF",
  TEXT_GRAY_MEDIUM: "#505450",
  TEXT_PURPLE_MEDIUM: "#463E59",
  TEXT_ORANGE_MEDIUM: "#695149",
  TEXT_DARK_GREEN: "#666C66",
  TEXT_DARK_PURPLE: "#655C80",
  TEXT_DARK_ORANGE: "#8C6C62",
  TEXT_ACTIVE: "#3E5741",

  // BORDERS COLORS
  BORDER_SECONDARY: "#E2E2E2",
  BORDER_TERTIARY: "#EEE",
  ACTIVE_CELL_BORDER: "#6C8B70",
  
  // ICON COLORS
  ICON_GREY: "#A3ACA3",
};
export default COLORS;
